Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder "../", "/vagrant"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    sudo apt-get install unzip
    wget -q https://releases.hashicorp.com/terraform/0.12.21/terraform_0.12.21_linux_amd64.zip
    unzip terraform_0.12.21_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    sudo apt-get update && sudo apt-get install -y libssl-dev libffi-dev python-dev python-pip
    sudo pip install ansible[azure]
    terraform --version
    ansible --version
    su vagrant
    export LC_ALL=C
  SHELL
end
